# Generated by Django 3.0.4 on 2020-03-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_type_id', models.IntegerField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Score', models.IntegerField(default=0)),
                ('Body', models.TextField()),
                ('ViewCount', models.IntegerField(default=0)),
                ('OwnerUserId', models.CharField(max_length=20)),
                ('LastActivityDate', models.DateTimeField(auto_now_add=True)),
                ('Title', models.TextField()),
                ('Tags', models.TextField()),
                ('AnswerCount', models.IntegerField(default=0)),
                ('CommentCount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'question_table',
            },
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_type_id', models.IntegerField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Score', models.IntegerField()),
                ('Body', models.TextField()),
                ('OwnerUserId', models.CharField(max_length=20)),
                ('LastActivityDate', models.DateTimeField(auto_now_add=True)),
                ('CommentCount', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DisplayData.QuestionModel')),
            ],
            options={
                'db_table': 'answer_table',
            },
        ),
    ]
